### ISSUE TITLE
Question on if the codes are complete?

### ISSUE THREAD

**Issue by jimazeyu** [lerftogo/lerftogo#1]
hen i tried to run the codes, the error happend in the line dinos = outputs["dino"],
 used print(outputs.keys()), but i only got basic components-dict_keys(['rgb', 'accumulation', 'depth', 'prop_depth_0', 'prop_depth_1', 'relevancy_0', 'relevancy_1', 'composited_0', 'composited_1']). It seems like it's still using the basic lerf model without dino embedded.
 If my operations have some problem, please figure it out, thanks.

**Comment by HuiHuiSun** [comment]
> e

Hello jimazeyu, have you resolved the problem?

**Comment by jimazeyu** [comment]
no

**Comment by HuiHuiSun** [comment]
> no

I don't understand how to use gen_grasp.py. I run the  python scripts/gen_grasp.py, but I just get a page link, then I open it and I don't know input what to the blank. Do you know how to use it?

**Comment by jimazeyu** [comment]
just follow the instruction, i remenber the query is seperated by ";", it's been a long time since i last read the code, but overall i think the code structure is easy to understand, you may take a  try:
_Have your data in a folder named data
Run python scripts/gen_grasp.py
Enter data folder name to train/load data
Enter object;part query in lerf query text box
Generate grasps_

**Comment by HuiHuiSun** [comment]
> just follow the instruction, i remenber the query is seperated by ";", it's been a long time since i last read the code, but overall i think the code structure is easy to understand, you may take a try: _Have your data in a folder named data Run python scripts/gen_grasp.py Enter data folder name to train/load data Enter object;part query in lerf query text box Generate grasps_

Thank you!

**Comment by HuiHuiSun** [comment]
Have you reproduced the results of the paper?

**Comment by jimazeyu** [comment]
I'm not sure since the problem i met hasnt been solved, you may try and if you succeed, please tell me

**Comment by HuiHuiSun** [comment]
> hen i tried to run the codes, the error happend in the line dinos = outputs["dino"], used print(outputs.keys()), but i only got basic components-dict_keys(['rgb', 'accumulation', 'depth', 'prop_depth_0', 'prop_depth_1', 'relevancy_0', 'relevancy_1', 'composited_0', 'composited_1']). It seems like it's still using the basic lerf model without dino embedded. If my operations have some problem, please figure it out, thanks.

It seems that I didn't meet the same error.

**Comment by jimazeyu** [comment]
what is your dataset

**Comment by HuiHuiSun** [comment]
> what is your dataset

I download the dataset from the page(https://lerftogo.github.io/desktop.html).

**Comment by jimazeyu** [comment]
I used flowes dataset, ca you visualize the grasps with query now?

**Comment by lerftogo** [comment]
Hey! Thanks for bringing this up, we are working to resolve this and make the code easier to use. Sorry for the delay

**Comment by HuiHuiSun** [comment]
> I used flowes dataset, ca you visualize the grasps with query now?

How to visualize the grasps with query?  I run  the calculate lerf query with no error.

**Comment by jimazeyu** [comment]
you should input a query like "flowers; pink" and click "query"

**Comment by jimazeyu** [comment]
> Hey! Thanks for bringing this up, we are working to resolve this and make the code easier to use. Sorry for the delay

Thanks

**Comment by HuiHuiSun** [comment]
> you should input a query like "flowers; pink" and click "query"

<img width="822" alt="Snipaste_2024-03-30_14-00-25" src="https://github.com/lerftogo/lerftogo/assets/109783750/90ce15c8-313e-454a-bb59-c33b507681c1">

I can visualize the flower dataset.

**Comment by jimazeyu** [comment]
i can also get the results now. By the way, what;s your training model, i mean lerf-lite, lerf-big or lerf or lerf-big, i used lerf-lite and the generated pcd is terrible

**Comment by HuiHuiSun** [comment]
> i can also get the results now. By the way, what;s your training model, i mean lerf-lite, lerf-big or lerf or lerf-big, i used lerf-lite and the generated pcd is terrible

I used  lerf-lite model, and the result is like the image. It seems that the pcd is vague.
